/**** Start of imports. If edited, may not auto-convert in the playground. ****/
var table = ee.FeatureCollection("projects/ee-kauelustosamorgadoufrn/assets/Limite_de_Bairros_RN");
/***** End of imports. If edited, may not auto-convert in the playground. *****/
Map.setCenter(-35.25, -5.8, 12);

//---- recorte da Zona Sul ----//
var alecrim = table.filter(ee.Filter.eq('BAIRRO', 'Alecrim'));
var areiaPreta = table.filter(ee.Filter.eq('BAIRRO', 'Areia Preta'));
var barroVermelho = table.filter(ee.Filter.eq('BAIRRO', 'Barro Vermelho'));
var bomPastor = table.filter(ee.Filter.eq('BAIRRO', 'Bom Pastor'));
var candelaria = table.filter(ee.Filter.eq('BAIRRO', 'Candel�ria'));
var capimMacio = table.filter(ee.Filter.eq('BAIRRO', 'Capim Macio'));
var cidadeAlta = table.filter(ee.Filter.eq('BAIRRO', 'Cidade Alta'));
var cidadeDaEsperanca = table.filter(ee.Filter.eq('BAIRRO', 'Cidade da Esperan�a'));
var cidadeNova = table.filter(ee.Filter.eq('BAIRRO', 'Cidade Nova'));
var dixSeptRosado = table.filter(ee.Filter.eq('BAIRRO', 'Dix-Sept Rosado'));
var felipeCamarao = table.filter(ee.Filter.eq('BAIRRO', 'Felipe Camar�o'));
var guarapes = table.filter(ee.Filter.eq('BAIRRO', 'Guarapes'));
var igapo = table.filter(ee.Filter.eq('BAIRRO', 'Igap�'));
var lagoaAzul = table.filter(ee.Filter.eq('BAIRRO', 'Lagoa Azul'));
var lagoaNova = table.filter(ee.Filter.eq('BAIRRO', 'Lagoa Nova'));
var lagoaSeca = table.filter(ee.Filter.eq('BAIRRO', 'Lagoa Seca'));
var maeLuiza = table.filter(ee.Filter.eq('BAIRRO', 'M�e Luiza'));
var neopolis = table.filter(ee.Filter.eq('BAIRRO', 'Ne�polis'));
var nordeste = table.filter(ee.Filter.eq('BAIRRO', 'Nordeste'));
var NSdaApresentacao = table.filter(ee.Filter.eq('BAIRRO', 'N.S. da Apresenta��o'));
var NSDoNazare = table.filter(ee.Filter.eq('BAIRRO', 'N.S. do Nazar�'));
var novaDescoberta = table.filter(ee.Filter.eq('BAIRRO', 'Nova Descoberta'));
var pajucara = table.filter(ee.Filter.eq('BAIRRO', 'Paju�ara'));
var parqueDasDunas = table.filter(ee.Filter.eq('BAIRRO', 'Parque das Dunas'));
var petropolis = table.filter(ee.Filter.eq('BAIRRO', 'Petr�polis'));
var pitimbu = table.filter(ee.Filter.eq('BAIRRO', 'Pitimbu'));
var planalto = table.filter(ee.Filter.eq('BAIRRO', 'Planalto'));
var pontaNegra = table.filter(ee.Filter.eq('BAIRRO', 'Ponta Negra'));
var potengi = table.filter(ee.Filter.eq('BAIRRO', 'Potengi'));
var praiaDoMeio = table.filter(ee.Filter.eq('BAIRRO', 'Praia do Meio'));
var quintas = table.filter(ee.Filter.eq('BAIRRO', 'Quintas'));
var redinha = table.filter(ee.Filter.eq('BAIRRO', 'Redinha'));
var ribeira = table.filter(ee.Filter.eq('BAIRRO', 'Ribeira'));
var rocas = table.filter(ee.Filter.eq('BAIRRO', 'Rocas'));
var salinas = table.filter(ee.Filter.eq('BAIRRO', 'Salinas'));
var santosReis = table.filter(ee.Filter.eq('BAIRRO', 'Santos Reis'));
var tirol = table.filter(ee.Filter.eq('BAIRRO', 'Tirol'));

//-- imprimindo Bairros --//
Map.addLayer(table, {}, 'Bairros');
Map.addLayer(alecrim, {}, 'Alecrim', false);
Map.addLayer(areiaPreta, {}, 'Areia Preta', false);
Map.addLayer(barroVermelho, {}, 'Barro Vermelho', false);
Map.addLayer(bomPastor, {}, 'Bom Pastor', false);
Map.addLayer(candelaria, {}, 'Candelária', false);
Map.addLayer(capimMacio, {}, 'Capim Macio', false);
Map.addLayer(cidadeAlta, {}, 'Cidade Alta', false);
Map.addLayer(cidadeDaEsperanca, {}, 'Cidade da Esperança', false);
Map.addLayer(cidadeNova, {}, 'Cidade Nova', false);
Map.addLayer(dixSeptRosado, {}, 'Dix-Sept Rosado', false);
Map.addLayer(felipeCamarao, {}, 'Felipe Camarão', false);
Map.addLayer(guarapes, {}, 'Guarapes', false);
Map.addLayer(igapo, {}, 'Igapó', false);
Map.addLayer(lagoaAzul, {}, 'Lagoa Azul', false);
Map.addLayer(lagoaNova, {}, 'Lagoa Nova', false);
Map.addLayer(lagoaSeca, {}, 'Lagoa Seca', false);
Map.addLayer(maeLuiza, {}, 'Mãe Luiza', false);
Map.addLayer(neopolis, {}, 'Neópolis', false);
Map.addLayer(nordeste, {}, 'Nordeste', false);
Map.addLayer(NSdaApresentacao, {}, 'N.S. da Apresentação', false);
Map.addLayer(NSDoNazare, {}, 'N.S. do Nazaré', false);
Map.addLayer(novaDescoberta, {}, 'Nova Descoberta', false);
Map.addLayer(pajucara, {}, 'Pajuçara', false);
Map.addLayer(parqueDasDunas, {}, 'Parque das Dunas', false);
Map.addLayer(petropolis, {}, 'Petrópolis', false);
Map.addLayer(pitimbu, {}, 'Pitimbu', false);
Map.addLayer(planalto, {}, 'Planalto', false);
Map.addLayer(pontaNegra, {}, 'Ponta Negra', false);
Map.addLayer(potengi, {}, 'Potengi', false);
Map.addLayer(praiaDoMeio, {}, 'Praia do Meio', false);
Map.addLayer(quintas, {}, 'Quintas', false);
Map.addLayer(redinha, {}, 'Redinha', false);
Map.addLayer(ribeira, {}, 'Ribeira', false);
Map.addLayer(rocas, {}, 'Rocas', false);
Map.addLayer(salinas, {}, 'Salinas', false);
Map.addLayer(santosReis, {}, 'Santos Reis', false);
Map.addLayer(tirol, {}, 'Tirol', false);